services:
  rabbitmq:
    image: rabbitmq:3.13.3-management
    container_name: rabbitmq
    networks:
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    networks:
      - default
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo_data:/data/db

  payment-service:
    build:
      context: ./PaymentManagement
      dockerfile: ./PaymentManagement/Dockerfile
    container_name: payment-management
    networks:
      - default
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      "WeBall:MongoDbConn": ${MONGODB_CONN}
      "WeBall:RabbitMqHost": ${RABBITMQ_HOST}

  notification-service:
    build:
      context: ./NotificationManagement
      dockerfile: ./NotificationManagement/Dockerfile
    container_name: notification-management
    networks:
      - default
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      "WeBall:RabbitMqHost": ${RABBITMQ_HOST}
      "WeBall:MailUsername": ${MAIL_USERNAME}
      "WeBall:MailPassword": ${MAIL_PASSWORD}

volumes:
  rabbitmq_data:
  mongo_data:
  mysql_data:

networks:
  default: